#!/usr/bin/env bash

set -e
pushd ~/nixos_config/

# if git diff --quiet '*.nix'; then
#   echo "No changes detected, exiting."
#   popd
#   exit 0
# fi

sudo nixos-rebuild switch --flake path:#default
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"

popd
